/* =====================================================================
   DATABASE KLAUSUL & REGULASI — Temuan Lapangan QSHE
   Boleh diedit. Format tiap baris: ["nomor", "judul / uraian"].
   - iso45 : ISO 45001:2018  (K3)
   - iso14 : ISO 14001:2026  (Lingkungan)
   - iso9  : ISO 9001:2026   (Mutu)
   - crit  : Kriteria audit SMK3 PP 50/2012
   - regs  : ["Nama peraturan lengkap", "topik singkat"]
   Setelah mengedit: naikkan VERSI di sw.js agar semua HP mendapat versi baru.
   ===================================================================== */
const KB = {
  elem: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12"
  ],
  subs: [
    "1.1",
    "1.2",
    "1.3",
    "1.4",
    "2.1",
    "2.2",
    "2.3",
    "2.4",
    "3.1",
    "3.2",
    "4.1",
    "4.2",
    "5.1",
    "5.2",
    "5.3",
    "5.4",
    "6.1",
    "6.2",
    "6.3",
    "6.4",
    "6.5",
    "6.6",
    "6.7",
    "6.8",
    "6.9",
    "7.1",
    "7.2",
    "7.3",
    "7.4",
    "8.1",
    "8.2",
    "8.3",
    "8.4",
    "9.1",
    "9.2",
    "9.3",
    "10.1",
    "10.2",
    "11.1",
    "12.1",
    "12.2",
    "12.3",
    "12.4",
    "12.5"
  ],
  crit: [
    ["1.1.1", "Terdapat kebijakan K3 yang tertulis, bertanggal, ditandatangani oleh pengusaha atau pengurus, secara jelas menyatakan tujuan dan sasaran K3 serta komitmen terhadap peningkatan K3."],
    ["1.1.2", "Kebijakan disusun oleh pengusaha dan/atau pengurus setelah melalui proses konsultasi dengan wakil tenaga kerja."],
    ["1.1.3", "Perusahaan mengkomunikasikan kebijakan K3 kepada seluruh tenaga kerja, tamu, kontraktor, pelanggan, dan pemasok dengan tata cara yang tepat."],
    ["1.1.4", "Kebijakan khusus dibuat untuk masalah K3 yang bersifat khusus."],
    ["1.1.5", "Kebijakan K3 dan kebijakan khusus lainnya ditinjau ulang secara berkala untuk menjamin bahwa kebijakan tersebut sesuai dengan perubahan yang terjadi dalam perusahaan dan dalam peraturan perundang-undangan."],
    ["1.2.1", "Tanggung jawab dan wewenang untuk mengambil tindakan dan melaporkan kepada semua pihak yang terkait dalam perusahaan di bidang K3 telah ditetapkan, diinformasikan dan didokumentasikan."],
    ["1.2.2", "Penunjukan penanggung jawab K3 harus sesuai peraturan perundang-undangan."],
    ["1.2.3", "Pimpinan unit kerja dalam suatu perusahaan bertanggung jawab atas kinerja K3 pada unit kerjanya."],
    ["1.2.4", "Pengusaha atau pengurus bertanggung jawab secara penuh untuk menjamin pelaksanaan SMK3."],
    ["1.2.5", "Petugas yang bertanggung jawab untuk penanganan keadaan darurat telah ditetapkan dan mendapatkan pelatihan."],
    ["1.2.6", "Perusahaan mendapatkan saran-saran dari para ahli di bidang K3 yang berasal dari dalam dan/atau luar perusahaan."],
    ["1.2.7", "Kinerja K3 termuat dalam laporan tahunan perusahaan atau laporan lain yang setingkat."],
    ["1.3.1", "Tinjauan terhadap penerapan SMK3 meliputi kebijakan, perencanaan, pelaksanaan, pemantauan dan evaluasi telah dilakukan, dicatat dan didokumentasikan."],
    ["1.3.2", "Hasil tinjauan dimasukkan dalam perencanaan tindakan manajemen."],
    ["1.3.3", "Pengurus harus meninjau ulang pelaksanaan SMK3 secara berkala untuk menilai kesesuaian dan efektivitas SMK3."],
    ["1.4.1", "Keterlibatan dan penjadwalan konsultasi tenaga kerja dengan wakil perusahaan didokumentasikan dan disebarluaskan ke seluruh tenaga kerja."],
    ["1.4.2", "Terdapat prosedur yang memudahkan konsultasi mengenai perubahan-perubahan yang mempunyai implikasi terhadap K3."],
    ["1.4.3", "Perusahaan telah membentuk P2K3 Sesuai dengan peraturan perundang-undangan."],
    ["1.4.4", "Ketua P2K3 adalah pimpinan puncak atau pengurus."],
    ["1.4.5", "Sekretaris P2K3 adalah ahli K3 sesuai dengan peraturan perundang-undangan."],
    ["1.4.6", "P2K3 menitikberatkan kegiatan pada pengembangan kebijakan dan prosedur mengendalikan risiko."],
    ["1.4.7", "Susunan pengurus P2K3 didokumentasikan dan diinformasikan kepada tenaga kerja."],
    ["1.4.8", "P2K3 mengadakan pertemuan secara teratur dan hasilnya disebarluaskan di tempat kerja."],
    ["1.4.9", "P2K3 melaporkan kegiatannya secara teratur sesuai dengan peraturan perundang-undangan."],
    ["1.4.10", "Dibentuk kelompok-kelompok kerja dan dipilih dari wakil-wakil tenaga kerja yang ditunjuk sebagai penanggung jawab K3 di tempat kerjanya dan kepadanya diberikan pelatihan sesuai dengan peraturan perundang-undangan."],
    ["1.4.11", "Susunan kelompok-kelompok kerja yang telah terbentuk didokumentasikan dan diinformasikan kepada tenaga kerja."],
    ["2.1.1", "Terdapat prosedur terdokumentasi untuk identifikasi potensi bahaya, penilaian, dan pengendalian risiko K3."],
    ["2.1.2", "Identifikasi potensi bahaya, penilaian, dan pengendalian risiko K3 sebagai rencana strategi K3 dilakukan oleh petugas yang berkompeten."],
    ["2.1.3", "Rencana strategi K3 sekurang-kurangya berdasarkan tinjauan awal, identifikasi potensi bahaya, penilaian, pengendalian risiko, dan peraturan perundang-undangan serta informasi K3 lain baik dari dalam maupun luar perusahaan."],
    ["2.1.4", "Rencana strategi K3 yang telah ditetapkan digunakan untuk mengendalikan risiko K3 dengan menetapkan tujuan dan sasaran yang dapat diukur dan menjadi prioritas serta menyediakan sumber daya."],
    ["2.1.5", "Rencana kerja dan rencana khusus yang berkaitan dengan produk, proses, proyek atau tempat kerja tertentu telah dibuat dengan menetapkan tujuan dan sasaran yang dapat diukur, menetapkan waktu pencapaian dan menyediakan sumber daya."],
    ["2.1.6", "Rencana K3 diselaraskan dengan rencana sistem manajemen perusahaan."],
    ["2.2.1", "Manual SMK3 meliputi kebijakan, tujuan, rencana, prosedur K3, instruksi kerja, formulir, catatan dan tanggung jawab serta wewenang tanggung jawab K3 untuk semua tingkatan dalam perusahaan."],
    ["2.2.2", "Terdapat manual khusus yang berkaitan dengan produk, proses, atau tempat kerja tertentu."],
    ["2.2.3", "Manual SMK3 mudah didapat oleh semua personil dalam perusahaan sesuai kebutuhan."],
    ["2.3.1", "Terdapat prosedur yang terdokumentasi untuk mengidentifikasi, memperoleh, memelihara dan memahami peraturan perundang-undangan, standar, pedoman teknis, dan persyaratan lain yang relevan dibidang K3 untuk seluruh tenaga kerja di perusahaan."],
    ["2.3.2", "Penanggung jawab untuk memelihara dan mendistribusikan informasi terbaru mengenai peraturan perundangan, standar, pedoman teknis, dan persyaratan lain telah ditetapkan"],
    ["2.3.3", "Persyaratan pada peraturan perundang-undangan, standar, pedoman teknis, dan persyaratan lain yang relevan di bidang K3 dimasukkan pada prosedur-prosedur dan petunjuk-petunjuk kerja."],
    ["2.3.4", "Perubahan pada peraturan perundang-undangan, standar, pedoman teknis, dan persyaratan lain yang relevan di bidang K3 digunakan untuk peninjauan prosedur-prosedur dan petunjuk-petunjuk kerja."],
    ["2.4.1", "Informasi yang dibutuhkan mengenai kegiatan K3 disebarluaskan secara sistematis kepada seluruh tenaga kerja, tamu, kontraktor, pelanggan, dan pemasok."],
    ["3.1.1", "Prosedur yang terdokumentasi mempertimbangkan identifikasi potensi bahaya, penilaian, dan pengendalian risiko yang dilakukan pada tahap perancangan dan modifikasi."],
    ["3.1.2", "Prosedur, instruksi kerja dalam penggunaan produk, pengoperasian mesin dan peralatan, instalasi, pesawat atau proses serta informasi lainnya yang berkaitan dengan K3 telah dikembangkan selama perancangan dan/atau modifikasi."],
    ["3.1.3", "Petugas yang berkompeten melakukan verifikasi bahwa perancangan dan/atau modifikasi memenuhi persyaratan K3 yang ditetapkan sebelum penggunaan hasil rancangan."],
    ["3.1.4", "Semua perubahan dan modifikasi perancangan yang mempunyai implikasi terhadap K3 diidentifikasikan, didokumentasikan, ditinjau ulang dan disetujui oleh petugas yang berwenang sebelum pelaksanaan."],
    ["3.2.1", "Prosedur yang terdokumentasi harus mampu mengidentifikasi bahaya dan menilai risiko K3 bagi tenaga kerja, lingkungan, dan masyarakat, dimana prosedur tersebut digunakan pada saat memasok barang dan jasa dalam suatu kontrak."],
    ["3.2.2", "Identifikasi bahaya dan penilaian risiko dilakukan pada tinjauan kontrak oleh petugas yang berkompeten."],
    ["3.2.3", "Kontrak ditinjau ulang untuk menjamin bahwa pemasok dapat memenuhi persyaratan K3 bagi pelanggan."],
    ["3.2.4", "Catatan tinjauan kontrak dipelihara dan didokumentasikan."],
    ["4.1.1", "Dokumen K3 mempunyai identifikasi status, wewenang, tanggal pengeluaran dan tanggal modifikasi."],
    ["4.1.2", "Penerima distribusi dokumen tercantum dalam dokumen tersebut."],
    ["4.1.3", "Dokumen K3 edisi terbaru disimpan secara sistematis pada tempat yang ditentukan."],
    ["4.1.4", "Dokumen usang segera disingkirkan dari penggunaannya sedangkan dokumen usang yang disimpan untuk keperluan tertentu diberi tanda khusus."],
    ["4.2.1", "Terdapat sistem untuk membuat, menyetujui perubahan terhadap dokumen K3."],
    ["4.2.2", "Dalam hal terjadi perubahan diberikan alasan terjadinya perubahan dan tertera dalam dokumen atau lampirannya dan menginformasikan kepada pihak terkait."],
    ["4.2.3", "Terdapat prosedur pengendalian dokumen atau daftar seluruh dokumen yang mencantumkan status dari setiap dokumen tersebut, dalam upaya mencegah penggunaan dokumen yang usang."],
    ["5.1.1", "Terdapat prosedur yang terdokumentasi yang dapat menjamin bahwa spesifikasi teknik dan informasi lain yang relevan dengan K3 telah diperiksa sebelum keputusan untuk membeli."],
    ["5.1.2", "Spesifikasi pembelian untuk setiap sarana produksi, zat kimia atau jasa harus dilengkapi spesifikasi yang sesuai dengan persyaratan peraturan perundang-undangan dan standar K3."],
    ["5.1.3", "Konsultasi dengan tenaga kerja yang kompeten pada saat keputusan pembelian, dilakukan untuk menetapkan persyaratan K3 yang dicantumkan dalam spesifikasi pembelian dan diinformasikan kepada tenaga kerja yang menggunakannya."],
    ["5.1.4", "Kebutuhan pelatihan, pasokan alat pelindung diri dan perubahan terhadap prosedur kerja harus dipertimbangkan sebelum pembelian dan penggunaannya."],
    ["5.1.5", "Persyaratan K3 dievaluasi dan menjadi pertimbangan dalam seleksi pembelian."],
    ["5.2.1", "Barang dan jasa yang dibeli diperiksa kesesuaiannya dengan spesifikasi pembelian."],
    ["5.3.1", "Barang dan jasa yang dipasok pelanggan, sebelum digunakan terlebih dahulu diidentifikasi potensi bahaya dan dinilai risikonya dan catatan tersebut dipelihara untuk memeriksa prosedur."],
    ["5.4.1", "Semua produk yang digunakan dalam proses produksi dapat diidentifikasi di seluruh tahapan produksi dan instalasi, jika terdapat potensi masalah K3."],
    ["5.4.2", "Terdapat prosedur yang terdokumentasi untuk penelusuran produk yang telah terjual, jika terdapat potensi masalah K3 di dalam penggunaannya."],
    ["6.1.1", "Petugas yang kompeten telah mengidentifikasi bahaya, menilai dan mengendalikan risiko yang timbul dari suatu proses kerja."],
    ["6.1.2", "Apabila upaya pengendalian risiko diperlukan, maka upaya tersebut ditetapkan melalui tingkat pengendalian."],
    ["6.1.3", "Terdapat prosedur atau petunjuk kerja yang terdokumentasi untuk mengendalikan risiko yang teridentifikasi dan dibuat atas dasar masukan dari personil yang kompeten serta tenaga kerja yang terkait dan disahkan oleh orang yang berwenang di perusahaan."],
    ["6.1.4", "Kepatuhan terhadap peraturan perundang-undangan, standar serta pedoman teknis yang relevan diperhatikan pada saat mengembangkan atau melakukan modifikasi atau petunjuk kerja."],
    ["6.1.5", "Terdapat sistem izin kerja untuk tugas berisiko tinggi."],
    ["6.1.6", "Alat pelindung diri disediakan sesuai kebutuhan dan digunakan secara benar serta selalu dipelihara dalam kondisi layak pakai."],
    ["6.1.7", "Alat pelindung diri yang digunakan dipastikan telah dinyatakan layak pakai sesuai dengan standar dan/atau peraturan perundang-undangan yang berlaku."],
    ["6.1.8", "Upaya pengendalian risiko dievaluasi secara berkala apabila terjadi ketidaksesuaian atau perubahan pada proses kerja."],
    ["6.2.1", "Dilakukan pengawasan untuk menjamin bahwa setiap pekerjaan dilaksanakan dengan aman dan mengikuti prosedur dan petunjuk kerja yang telah ditentukan."],
    ["6.2.2", "Setiap orang diawasi sesuai dengan tingkat kemampuan dan tingkat risiko tugas."],
    ["6.2.3", "Pengawas/penyelia ikut serta dalam identifikasi bahaya dan membuat upaya pengendalian."],
    ["6.2.4", "Pengawas/penyelia diikutsertakan dalam melakukan penyelidikan dan pembuatan laporan terhadap terjadinya kecelakaan dan penyakit akibat kerja serta wajib menyerahkan laporan dan saran-saran kepada pengusaha atau pengurus."],
    ["6.2.5", "Pengawas/penyelia ikut serta dalam proses konsultasi."],
    ["6.3.1", "Persyaratan tugas tertentu termasuk persyaratan kesehatan diidentifikasi dan dipakai untuk menyeleksi dan menempatkan tenaga kerja."],
    ["6.3.2", "Penugasan pekerjaan harus berdasarkan kemampuan dan keterampilan serta kewenangan yang dimiliki."],
    ["6.4.1", "Pengusaha atau pengurus melakukan penilaian risiko lingkungan kerja untuk mengetahui daerah-daerah yang memerlukan pembatasan izin masuk."],
    ["6.4.2", "Terdapat pengendalian atas daerah/tempat dengan pembatasan izin masuk."],
    ["6.4.3", "Tersedianya fasilitas dan layanan di tempat kerja sesuai dengan standar dan pedoman teknis."],
    ["6.4.4", "Rambu-rambu K3 harus dipasang sesuai dengan standar dan pedoman teknis."],
    ["6.5.1", "Penjadualan pemeriksaan dan pemeliharaan sarana produksi serta peralatan mencakup verifikasi alat-alat pengaman serta persyaratan yang ditetapkan oleh peraturan perundang-undangan, standar dan pedoman teknis yang relevan."],
    ["6.5.2", "Semua catatan yang memuat data secara rinci dari kegiatan pemeriksaan, pemeliharaan, perbaikan dan perubahan yang dilakukan atas sarana dan peralatan produksi harus disimpan dan dipelihara."],
    ["6.5.3", "Sarana dan peralatan produksi memiliki sertifikat yang masih berlaku sesuai dengan persyaratan peraturan perundang-undangan dan standar."],
    ["6.5.4", "Pemeriksaan, pemeliharaan, perawatan, perbaikan dan setiap perubahan harus dilakukan petugas yang kompeten dan berwenang."],
    ["6.5.5", "Terdapat prosedur untuk menjamin bahwa Jika terjadi perubahan terhadap sarana dan peralatan produksi, perubahan tersebut harus sesuai dengan persyaratan peraturan perundang-undangan, standar dan pedoman teknis yang relevan."],
    ["6.5.6", "Terdapat prosedur permintaan pemeliharaan sarana dan peralatan produksi dengan kondisi K3 yang tidak memenuhi persyaratan dan perlu segera diperbaiki."],
    ["6.5.7", "Terdapat sistem untuk penandaan bagi peralatan yang sudah tidak aman lagi untuk digunakan atau sudah tidak digunakan."],
    ["6.5.8", "Apabila diperlukan dilakukan penerapan sistem penguncian pengoperasian (lock out system) untuk mencegah agar sarana produksi tidak dihidupkan sebelum saatnya."],
    ["6.5.9", "Terdapat prosedur yang dapat menjamin keselamatan dan kesehatan tenaga kerja atau orang lain yang berada didekat sarana dan peralatan produksi pada saat proses pemeriksaan, pemeliharaan, perbaikan dan perubahan."],
    ["6.5.10", "Terdapat penanggung jawab untuk menyetujui bahwa sarana dan peralatan produksi telah aman digunakan setelah proses pemeliharaan, perawatan, perbaikan atau perubahan."],
    ["6.6.1", "Apabila perusahaan dikontrak untuk menyediakan pelayanan yang tunduk pada standar dan peraturan perundang-undangan mengenai K3, maka perlu disusun prosedur untuk menjamin bahwa pelayanan memenuhi persyaratan."],
    ["6.6.2", "Apabila perusahaan diberi pelayanan melalui kontrak, dan pelayanan tunduk pada standar dan peraturan perundang-undangan K3, maka perlu disusun prosedur untuk menjamin bahwa pelayanan memenuhi persyaratan."],
    ["6.7.1", "Keadaan darurat yang potensial di dalam dan/atau di luar tempat kerja telah diidentifikasi dan prosedur keadaan darurat telah didokumentasikan dan diinformasikan agar diketahui oleh seluruh orang yang ada di tempat kerja."],
    ["6.7.2", "Penyediaan alat/sarana dan prosedur keadaan darurat berdasarkan hasil identifikasi dan diuji serta ditinjau secara rutin oleh petugas yang berkompeten dan berwenang."],
    ["6.7.3", "Tenaga kerja mendapat instruksi dan pelatihan mengenai prosedur keadaan darurat yang sesuai dengan tingkat risiko."],
    ["6.7.4", "Petugas penanganan keadaan darurat ditetapkan dan diberikan pelatihan khusus serta diinformasikan kepada seluruh orang yang ada di tempat kerja."],
    ["6.7.5", "Instruksi/prosedur keadaan darurat dan hubungan keadaan darurat diperlihatkan secara jelas dan menyolok serta diketahui oleh seluruh tenaga kerja di perusahaan."],
    ["6.7.6", "Peralatan, dan sistem tanda bahaya keadaan darurat disediakan, diperiksa, diuji dan dipelihara secara berkala sesuai dengan peraturan perundang-undangan, standar dan pedoman teknis yang relevan."],
    ["6.7.7", "Jenis, jumlah, penempatan dan kemudahan untuk mendapatkan alat keadaan darurat telah sesuai dengan peraturan perundang-undangan atau standar dan dinilai oleh petugas yang berkompeten dan berwenang."],
    ["6.8.1", "Perusahaan telah mengevaluasi alat P3K dan menjamin bahwa sistem P3K yang ada memenuhi peraturan perundang-undangan, standar dan pedoman teknis."],
    ["6.8.2", "Petugas P3K telah dilatih dan ditunjuk sesuai dengan peraturan perundangan-undangan."],
    ["6.9.1", "Prosedur untuk pemulihan kondisi tenaga kerja maupun sarana dan peralatan produksi yang mengalami kerusakan telah ditetapkan dan dapat diterapkan sesegera mungkin setelah terjadinya kecelakaan dan penyakit akibat kerja."],
    ["7.1.1", "Pemeriksaan/inspeksi terhadap tempat kerja dan cara kerja dilaksanakan secara teratur."],
    ["7.1.2", "Pemeriksaan/inspeksi dilaksanakan oleh petugas yang berkompeten dan berwenang yang telah memperoleh pelatihan mengenai identifikasi bahaya."],
    ["7.1.3", "Pemeriksaan/inspeksi mencari masukan dari tenaga kerja yang melakukan tugas di tempat yang diperiksa."],
    ["7.1.4", "Daftar periksa (check list) tempat kerja telah disusun untuk digunakan pada saat pemeriksaan/inspeksi."],
    ["7.1.5", "Laporan pemeriksaan/inspeksi berisi rekomendasi untuk tindakan perbaikan dan diajukan kepada pengurus dan P2K3 sesuai dengan kebutuhan."],
    ["7.1.6", "Pengusaha atau pengurus telah menetapkan penanggung jawab untuk pelaksanaan tindakan perbaikan dari hasil laporan pemeriksaan/inspeksi."],
    ["7.1.7", "Tindakan perbaikan dari hasil laporan pemeriksaan/inspeksi dipantau untuk menentukan efektifitasnya."],
    ["7.2.1", "Pemantauan/pengukuran lingkungan kerja dilaksanakan secara teratur dan hasilnya didokumentasikan, dipelihara dan digunakan untuk penilaian dan pengendalian risiko."],
    ["7.2.2", "Pemantauan/pengukuran lingkungan kerja meliputi faktor fisik, kimia, biologi, ergonomi dan psikologi."],
    ["7.2.3", "Pemantauan/pengukuran lingkungan kerja dilakukan oleh petugas atau pihak yang berkompeten dan berwenang dari dalam dan/atau luar perusahaan."],
    ["7.3.1", "Terdapat prosedur yang terdokumentasi mengenai identifikasi, kalibrasi, pemeliharaan dan penyimpanan untuk alat pemeriksaan, ukur dan uji mengenai K3."],
    ["7.3.2", "Alat dipelihara dan dikalibrasi oleh petugas atau pihak yang berkompeten dan berwenang dari dalam dan/atau luar perusahaan."],
    ["7.4.1", "Dilakukan pemantauan kesehatan tenaga kerja yang bekerja pada tempat kerja yang mengandung potensi bahaya tinggi sesuai dengan peraturan perundang-undangan."],
    ["7.4.2", "Pengusaha atau pengurus telah melaksanakan identifikasi keadaan dimana pemeriksaan kesehatan tenaga kerja perlu dilakukan dan telah melaksanakan sistem untuk membantu pemeriksaan ini."],
    ["7.4.3", "Pemeriksaan kesehatan tenaga kerja dilakukan oleh dokter pemeriksa yang ditunjuk sesuai peraturan perundang-undangan."],
    ["7.4.4", "Perusahaan menyediakan pelayanan kesehatan kerja sesuai peraturan perundang-undangan."],
    ["7.4.5", "Catatan mengenai pemantauan kesehatan tenaga kerja dibuat sesuai dengan peraturan perundang-undangan."],
    ["8.1.1", "Terdapat prosedur pelaporan bahaya yang berhubungan dengan K3 dan prosedur ini diketahui oleh tenaga kerja."],
    ["8.2.1", "Terdapat prosedur terdokumentasi yang menjamin bahwa semua kecelakaan kerja, penyakit akibat kerja, kebakaran atau peledakan serta kejadian berbahaya lainnya di tempat kerja dicatat dan dilaporkan sesuai dengan peraturan perundang-undangan."],
    ["8.3.1", "Tempat kerja/perusahaan mempunyai prosedur pemeriksaan dan pengkajian kecelakaan kerja dan penyakit akibat kerja."],
    ["8.3.2", "Pemeriksaan dan pengkajian kecelakaan kerja dilakukan oleh petugas atau Ahli K3 yang ditunjuk sesuai peraturan perundang-undangan atau pihak lain yang berkompeten dan berwenang."],
    ["8.3.3", "Laporan pemeriksaan dan pengkajian berisi tentang sebab dan akibat serta rekomendasi/saran dan jadwal waktu pelaksanaan usaha perbaikan."],
    ["8.3.4", "Penanggung jawab untuk melaksanakan tindakan perbaikan atas laporan pemeriksaan dan pengkajian telah ditetapkan."],
    ["8.3.5", "Tindakan perbaikan diinformasikan kepada tenaga kerja yang bekerja di tempat terjadinya kecelakaan."],
    ["8.3.6", "Pelaksanaan tindakan perbaikan dipantau, didokumentasikan dan diinformasikan ke seluruh tenaga kerja."],
    ["8.4.1", "Terdapat prosedur untuk menangani masalah keselamatan dan kesehatan yang timbul dan sesuai dengan peraturan perundang-undangan yang berlaku."],
    ["9.1.1", "Terdapat prosedur untuk mengidentifikasi potensi bahaya dan menilai risiko yang berhubungan dengan penanganan secara manual dan mekanis."],
    ["9.1.2", "Identifikasi bahaya dan penilaian risiko dilaksanakan oleh petugas yang berkompeten dan berwenang."],
    ["9.1.3", "Pengusaha atau pengurus menerapkan dan meninjau cara pengendalian risiko yang berhubungan dengan penanganan secara manual atau mekanis."],
    ["9.1.4", "Terdapat prosedur untuk penanganan bahan meliputi metode pencegahan terhadap kerusakan, tumpahan dan/atau kebocoran."],
    ["9.2.1", "Terdapat prosedur yang menjamin bahwa bahan disimpan dan dipindahkan dengan cara yang aman sesuai dengan peraturan perundang-undangan."],
    ["9.2.2", "Terdapat prosedur yang menjelaskan persyaratan pengendalian bahan yang dapat rusak atau kadaluarsa."],
    ["9.2.3", "Terdapat prosedur yang menjamin bahwa bahan dibuang dengan cara yang aman sesuai dengan peraturan perundang-undangan."],
    ["9.3.1", "Perusahaan telah mendokumentasikan dan menerapkan prosedur mengenai penyimpanan, penanganan dan pemindahan BKB sesuai dengan persyaratan peraturan perundang-undangan, standar dan pedoman teknis yang relevan."],
    ["9.3.2", "Terdapat Lembar Data Keselamatan BKB (Material Safety Data Sheets) meliputi keterangan mengenai keselamatan bahan sebagaimana diatur pada peraturan perundang-undangan dan dengan mudah dapat diperoleh."],
    ["9.3.3", "Terdapat sistem untuk mengidentifikasi dan pemberian label secara jelas pada bahan kimia berbahaya."],
    ["9.3.4", "Rambu peringatan bahaya terpasang sesuai dengan persyaratan peraturan perundang-undangan dan/atau standar yang relevan."],
    ["9.3.5", "Penanganan BKB dilakukan oleh petugas yang berkompeten dan berwenang."],
    ["10.1.1", "Pengusaha atau pengurus telah mendokumentasikan dan menerapkan prosedur pelaksanaan identifikasi, pengumpulan, pengarsipan, pemeliharaan, penyimpanan dan penggantian catatan K3."],
    ["10.1.2", "Peraturan perundang-undangan, standar dan pedoman teknis K3 yang relevan dipelihara pada tempat yang mudah didapat."],
    ["10.1.3", "Terdapat prosedur yang menentukan persyaratan untuk menjaga kerahasiaan catatan."],
    ["10.1.4", "Catatan kompensasi kecelakaan dan rehabilitasi kesehatan tenaga kerja dipelihara."],
    ["10.2.1", "Data K3 yang terbaru dikumpulkan dan dianalisa."],
    ["10.2.2", "Laporan rutin kinerja K3 dibuat dan disebarluaskan di dalam tempat kerja."],
    ["11.1.1", "Audit internal SMK3 yang terjadwal dilaksanakan untuk memeriksa kesesuaian kegiatan perencanaan dan untuk menentukan efektifitas kegiatan tersebut."],
    ["11.1.2", "Audit internal SMK3 dilakukan oleh petugas yang independen, berkompeten dan berwenang."],
    ["11.1.3", "Laporan audit didistribusikan kepada pengusaha atau pengurus dan petugas lain yang berkepentingan dan dipantau untuk menjamin dilakukannya tindakan perbaikan."],
    ["12.1.1", "Analisis kebutuhan pelatihan K3 sesuai persyaratan peraturan perundang-undangan telah dilakukan."],
    ["12.1.2", "Rencana pelatihan K3 bagi semua tingkatan telah disusun."],
    ["12.1.3", "Jenis pelatihan K3 yang dilakukan harus disesuaikan dengan kebutuhan untuk pengendalian potensi bahaya."],
    ["12.1.4", "Pelatihan dilakukan oleh orang atau badan yang berkompeten dan berwenang sesuai peraturan perundang-undangan."],
    ["12.1.5", "Terdapat fasilitas dan sumber daya memadai untuk pelaksanaan pelatihan yang efektif."],
    ["12.1.6", "Pengusaha atau pengurus mendokumentasikan dan menyimpan catatan seluruh pelatihan."],
    ["12.1.7", "Program pelatihan ditinjau secara teratur untuk menjamin agar tetap relevan dan efektif."],
    ["12.2.1", "Anggota manajemen eksekutif dan pengurus berperan serta dalam pelatihan yang mencakup penjelasan tentang kewajiban hukum dan prinsip-prinsip serta pelaksanaan K3."],
    ["12.2.2", "Manajer dan pengawas/penyelia menerima pelatihan yang sesuai dengan peran dan tanggung jawab mereka."],
    ["12.3.1", "Pelatihan diberikan kepada semua tenaga kerja termasuk tenaga kerja baru dan yang dipindahkan agar mereka dapat melaksanakan tugasnya secara aman."],
    ["12.3.2", "Pelatihan diberikan kepada tenaga kerja apabila di tempat kerjanya terjadi perubahan sarana produksi atau proses."],
    ["12.3.3", "Pengusaha atau pengurus memberikan pelatihan penyegaran kepada semua tenaga kerja."],
    ["12.4.1", "Terdapat prosedur yang menetapkan persyaratan untuk memberikan taklimat (briefing) kepada pengunjung dan mitra kerja guna menjamin K3."],
    ["12.5.1", "Perusahaan mempunyai sistem yang menjamin kepatuhan terhadap persyaratan lisensi atau kualifikasi sesuai dengan peraturan perundangan untuk melaksanakan tugas khusus, melaksanakan pekerjaan atau mengoperasikan peralatan."]
  ],
  iso45: [
    ["4.1", "Memahami organisasi dan konteksnya"],
    ["4.2", "Kebutuhan dan harapan pekerja serta pihak berkepentingan"],
    ["4.3", "Ruang lingkup SMK3"],
    ["4.4", "Sistem manajemen K3"],
    ["5.1", "Kepemimpinan dan komitmen (termasuk perlindungan pelapor)"],
    ["5.2", "Kebijakan K3"],
    ["5.3", "Peran, tanggung jawab dan wewenang"],
    ["5.4", "Konsultasi dan partisipasi pekerja"],
    ["6.1.1", "Tindakan menangani risiko dan peluang - umum"],
    ["6.1.2.1", "Identifikasi bahaya (rutin/non-rutin, infrastruktur, peralatan, faktor manusia, darurat)"],
    ["6.1.2.2", "Penilaian risiko K3"],
    ["6.1.2.3", "Penilaian peluang K3"],
    ["6.1.3", "Penentuan persyaratan hukum dan persyaratan lain"],
    ["6.1.4", "Perencanaan tindakan (hierarki pengendalian)"],
    ["6.2.1", "Sasaran K3"],
    ["6.2.2", "Perencanaan pencapaian sasaran K3"],
    ["7.1", "Sumber daya"],
    ["7.2", "Kompetensi"],
    ["7.3", "Kepedulian (awareness), termasuk hak menghindar dari bahaya serius"],
    ["7.4.1", "Komunikasi - umum"],
    ["7.4.2", "Komunikasi internal"],
    ["7.4.3", "Komunikasi eksternal"],
    ["7.5.1", "Informasi terdokumentasi - umum"],
    ["7.5.2", "Pembuatan dan pembaruan informasi terdokumentasi"],
    ["7.5.3", "Pengendalian informasi terdokumentasi"],
    ["8.1.1", "Perencanaan dan pengendalian operasi - umum (kriteria proses, adaptasi kerja)"],
    ["8.1.2", "Eliminasi bahaya dan pengurangan risiko K3 (hierarki pengendalian, APD)"],
    ["8.1.3", "Manajemen perubahan"],
    ["8.1.4.1", "Pengadaan - umum"],
    ["8.1.4.2", "Kontraktor"],
    ["8.1.4.3", "Alih daya"],
    ["8.2", "Kesiapsiagaan dan tanggap darurat (P3K, pelatihan, simulasi)"],
    ["9.1.1", "Pemantauan, pengukuran, analisis dan evaluasi kinerja (termasuk kalibrasi alat ukur)"],
    ["9.1.2", "Evaluasi kepatuhan"],
    ["9.2", "Audit internal"],
    ["9.3", "Tinjauan manajemen"],
    ["10.2", "Insiden, ketidaksesuaian dan tindakan korektif"],
    ["10.3", "Peningkatan berkelanjutan"]
  ],
  iso14: [
    ["4.1", "Memahami organisasi dan konteksnya (termasuk kondisi lingkungan: polusi, sumber daya alam, perubahan iklim, biodiversitas)"],
    ["4.2", "Kebutuhan dan harapan pihak berkepentingan"],
    ["4.3", "Ruang lingkup SML"],
    ["4.4", "Sistem manajemen lingkungan"],
    ["5.1", "Kepemimpinan dan komitmen"],
    ["5.2", "Kebijakan lingkungan (perlindungan lingkungan, pencegahan pencemaran)"],
    ["5.3", "Peran, tanggung jawab dan wewenang"],
    ["6.1.1", "Tindakan menangani risiko dan peluang - umum"],
    ["6.1.2", "Aspek lingkungan (perspektif siklus hidup, kondisi normal/abnormal/darurat, aspek penting)"],
    ["6.1.3", "Kewajiban penaatan"],
    ["6.1.4", "Risiko dan peluang"],
    ["6.1.5", "Perencanaan tindakan"],
    ["6.2.1", "Sasaran lingkungan"],
    ["6.2.2", "Perencanaan tindakan mencapai sasaran lingkungan"],
    ["6.3", "Perencanaan perubahan"],
    ["7.1", "Sumber daya"],
    ["7.2", "Kompetensi"],
    ["7.3", "Kepedulian (awareness)"],
    ["7.4", "Komunikasi"],
    ["7.5", "Informasi terdokumentasi"],
    ["8.1", "Perencanaan dan pengendalian operasi (kriteria operasi, penyedia eksternal/kontraktor, siklus hidup)"],
    ["8.2", "Kesiapsiagaan dan tanggap darurat (tumpahan, kebakaran, banjir)"],
    ["9.1.1", "Pemantauan, pengukuran, analisis dan evaluasi (alat ukur terkalibrasi)"],
    ["9.1.2", "Evaluasi kepatuhan"],
    ["9.2", "Audit internal"],
    ["9.3", "Tinjauan manajemen"],
    ["10.1", "Peningkatan berkelanjutan"],
    ["10.2", "Ketidaksesuaian dan tindakan korektif"]
  ],
  iso9: [
    ["4.1", "Memahami organisasi dan konteksnya (termasuk relevansi perubahan iklim)"],
    ["4.2", "Kebutuhan dan harapan pihak berkepentingan (persyaratan relevan yang ditangani SMM)"],
    ["4.3", "Ruang lingkup SMM"],
    ["4.4", "Sistem manajemen mutu dan prosesnya"],
    ["5.1.1", "Kepemimpinan dan komitmen - umum (termasuk budaya mutu dan perilaku etis)"],
    ["5.1.2", "Fokus pelanggan"],
    ["5.2", "Kebijakan mutu"],
    ["5.3", "Peran, tanggung jawab dan wewenang"],
    ["6.1.1", "Tindakan menangani risiko dan peluang - umum"],
    ["6.1.2", "Risiko (penentuan, analisis, evaluasi, tindakan)"],
    ["6.1.3", "Peluang (penentuan, analisis, evaluasi, tindakan)"],
    ["6.2", "Sasaran mutu dan perencanaannya"],
    ["6.3", "Perencanaan perubahan (komunikasi, pemantauan, tinjauan hasil perubahan)"],
    ["7.1.3", "Infrastruktur"],
    ["7.1.4", "Lingkungan untuk operasi proses"],
    ["7.1.5", "Sumber daya pemantauan dan pengukuran (ketertelusuran/kalibrasi)"],
    ["7.1.6", "Pengetahuan organisasi (dipertahankan, diterapkan, dibagikan)"],
    ["7.2", "Kompetensi"],
    ["7.3", "Kepedulian (termasuk budaya mutu dan perilaku etis)"],
    ["7.4", "Komunikasi"],
    ["7.5", "Informasi terdokumentasi"],
    ["8.1", "Perencanaan dan pengendalian operasi"],
    ["8.2", "Persyaratan produk dan jasa (komunikasi pelanggan, termasuk tindakan kontinjensi)"],
    ["8.4", "Pengendalian proses, produk dan jasa dari penyedia eksternal"],
    ["8.5.1", "Pengendalian produksi dan penyediaan jasa (informasi kerja terkini tersedia di tempat kerja)"],
    ["8.5.2", "Identifikasi dan mampu telusur"],
    ["8.5.3", "Milik pelanggan atau penyedia eksternal"],
    ["8.5.4", "Preservasi (penyimpanan, penanganan, pengemasan)"],
    ["8.5.5", "Kegiatan pasca pengiriman"],
    ["8.5.6", "Pengendalian perubahan"],
    ["8.6", "Pelepasan produk dan jasa"],
    ["8.7", "Pengendalian keluaran yang tidak sesuai"],
    ["9.1", "Pemantauan, pengukuran, analisis dan evaluasi (kepuasan pelanggan)"],
    ["9.2", "Audit internal (program, kriteria, lingkup, dan tujuan tiap audit)"],
    ["9.3", "Tinjauan manajemen"],
    ["10.1", "Peningkatan berkelanjutan (dahulu 10.3)"],
    ["10.2", "Ketidaksesuaian dan tindakan korektif"]
  ],
  regs: [
    ["UU No. 1 Tahun 1970 tentang Keselamatan Kerja", "kewajiban umum K3 pengurus & tenaga kerja, syarat keselamatan kerja (Pasal 3), kewajiban pengurus (Pasal 14)"],
    ["PP No. 50 Tahun 2012 tentang Penerapan Sistem Manajemen K3", "SMK3, kriteria audit SMK3"],
    ["PP No. 88 Tahun 2019 tentang Kesehatan Kerja", "kesehatan kerja, pelayanan kesehatan kerja"],
    ["Permenaker No. 5 Tahun 2018 tentang K3 Lingkungan Kerja", "faktor fisika/kimia/biologi/ergonomi/psikologi, housekeeping, sanitasi, penerangan, air minum, kebersihan tempat kerja"],
    ["Permenakertrans No. PER.08/MEN/VII/2010 tentang Alat Pelindung Diri", "APD: penyediaan, kelayakan, pemeliharaan, pemusnahan APD rusak"],
    ["Permenaker No. 8 Tahun 2020 tentang K3 Pesawat Angkat dan Pesawat Angkut", "crane, hoist, forklift, lifting gear, sling, chain block, riksa uji, operator berlisensi"],
    ["Permenaker No. 38 Tahun 2016 tentang K3 Pesawat Tenaga dan Produksi", "mesin, kompresor, genset, mesin perkakas, guarding, riksa uji"],
    ["Permenaker No. 37 Tahun 2016 tentang K3 Bejana Tekanan dan Tangki Timbun", "tabung gas, kompresor/air receiver, tangki BBM, akumulator"],
    ["Permenaker No. 12 Tahun 2015 tentang K3 Listrik di Tempat Kerja", "instalasi listrik, panel, kabel, grounding, LOTO listrik"],
    ["Permenaker No. 9 Tahun 2016 tentang K3 dalam Pekerjaan pada Ketinggian", "bekerja di ketinggian, tangga, perancah, full body harness, akses ke atas unit"],
    ["Permenaker No. 11 Tahun 2023 tentang K3 Ruang Terbatas", "confined space, tangki, izin kerja ruang terbatas"],
    ["Permenakertrans No. PER.04/MEN/1980 tentang Syarat-syarat Pemasangan dan Pemeliharaan APAR", "APAR: penempatan, inspeksi, tanda, tekanan, masa isi ulang"],
    ["Kepmenaker No. KEP.186/MEN/1999 tentang Unit Penanggulangan Kebakaran di Tempat Kerja", "petugas peran kebakaran, jalur evakuasi, tanda darurat, latihan evakuasi"],
    ["Permenakertrans No. PER.15/MEN/VIII/2008 tentang Pertolongan Pertama pada Kecelakaan di Tempat Kerja", "kotak P3K, isi P3K, petugas P3K"],
    ["Kepmenaker No. KEP.187/MEN/1999 tentang Pengendalian Bahan Kimia Berbahaya di Tempat Kerja", "bahan kimia, LDKB/SDS, label, penyimpanan bahan kimia"],
    ["Permenaker No. PER.04/MEN/1987 tentang P2K3 serta Tata Cara Penunjukan Ahli K3", "P2K3, ahli K3"],
    ["Permenkes No. 48 Tahun 2016 tentang Standar K3 Perkantoran", "perkantoran: ergonomi kursi/meja, pencahayaan, kebersihan, toilet, pantry"],
    ["Permen PU No. 26/PRT/M/2008 tentang Persyaratan Teknis Sistem Proteksi Kebakaran pada Bangunan Gedung dan Lingkungan", "proteksi kebakaran gedung, sarana jalan keluar/tangga darurat, hidran, sprinkler"],
    ["UU No. 22 Tahun 2009 tentang Lalu Lintas dan Angkutan Jalan", "kendaraan operasional, SIM, laik jalan, muatan, sabuk keselamatan"],
    ["Kepmen ESDM No. 1827 K/30/MEM/2018 tentang Pedoman Pelaksanaan Kaidah Teknik Pertambangan yang Baik", "site tambang: K3 pertambangan, kelayakan sarana, jalan tambang, KO/pengawas"],
    ["Permen ESDM No. 26 Tahun 2018 tentang Pelaksanaan Kaidah Pertambangan yang Baik dan Pengawasan Pertambangan Minerba", "site tambang: kaidah pertambangan yang baik, pengawasan"],
    ["UU No. 32 Tahun 2009 tentang Perlindungan dan Pengelolaan Lingkungan Hidup (sebagaimana diubah UU No. 6 Tahun 2023)", "kewajiban umum lingkungan, pencemaran"],
    ["PP No. 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup", "persetujuan lingkungan, pengelolaan limbah B3, TPS LB3, air limbah, emisi"],
    ["Permen LHK No. 6 Tahun 2021 tentang Tata Cara dan Persyaratan Pengelolaan Limbah B3", "TPS limbah B3: bangunan, masa simpan, kemasan, logbook, neraca, manifest, oli bekas, filter, majun terkontaminasi"],
    ["Permen LH No. 14 Tahun 2013 tentang Simbol dan Label Limbah B3", "simbol dan label kemasan limbah B3"],
    ["Permen LHK No. 9 Tahun 2024 tentang Pengelolaan Sampah yang Mengandung B3 dan Limbah B3", "sampah mengandung B3 (baterai, lampu, kemasan), pemilahan tempat sampah B3"],
    ["UU No. 18 Tahun 2008 tentang Pengelolaan Sampah", "sampah domestik, pemilahan"],
    ["Permen LHK No. P.68/Menlhk/Setjen/Kum.1/8/2016 tentang Baku Mutu Air Limbah Domestik", "air limbah domestik, septic tank, IPAL domestik"],
    ["Permen LH No. 5 Tahun 2014 tentang Baku Mutu Air Limbah", "air limbah kegiatan (cucian unit, oil trap/OWS)"],
    ["Permen LHK No. 11 Tahun 2021 tentang Baku Mutu Emisi Mesin dengan Pembakaran Dalam", "emisi genset/mesin diesel stasioner"],
    ["Kepmen LH No. 48 Tahun 1996 tentang Baku Tingkat Kebisingan", "kebisingan lingkungan"]
  ]
};
